SELECT
	DATE_PART('century', A.FIRST_TERM) AS FIRST_CENTURY,
	A.FIRST_TYPE,
	COUNT(DISTINCT A.ID_BIOGUIDE) AS COHORT,
	COUNT(B.TERM_START) AS TOTAL_NUMBER_OF_TERMS,
	COUNT(B.TERM_START) * 1.0 / COUNT(DISTINCT A.ID_BIOGUIDE) AS AVG_NO_TERMS_PER_LEG
FROM
	(
		SELECT DISTINCT
			ID_BIOGUIDE,
			FIRST_VALUE(TERM_TYPE) OVER (
				PARTITION BY
					ID_BIOGUIDE
				ORDER BY
					TERM_START
			) AS FIRST_TYPE,
			MIN(TERM_START) OVER (
				PARTITION BY
					ID_BIOGUIDE
			) AS FIRST_TERM,
			MIN(TERM_START) OVER (
				PARTITION BY
					ID_BIOGUIDE
			) + INTERVAL '10 years' AS FIRST_PLUS_10
		FROM
			LEGISLATORS_TERMS
	) A
	LEFT JOIN LEGISLATORS_TERMS B ON A.ID_BIOGUIDE = B.ID_BIOGUIDE
	AND B.TERM_START BETWEEN A.FIRST_TERM AND A.FIRST_PLUS_10
GROUP BY
	1,
	2
ORDER BY
	1