SELECT
	*,
	FIRST_VALUE(YEARLY_SALES) OVER (
		PARTITION BY
			KIND_OF_BUSINESS
		ORDER BY
			SALES_YEAR
	) AS INDEX_VAL,
	(YEARLY_SALES / FIRST_VALUE(YEARLY_SALES) OVER (
		PARTITION BY
			KIND_OF_BUSINESS
		ORDER BY
			SALES_YEAR
	) - 1) * 100 AS PCT_chng_FROM_INDEX
FROM
	(
		SELECT
			DATE_PART('year', SALES_MONTH) AS SALES_YEAR,
			KIND_OF_BUSINESS,
			SUM(SALES) AS YEARLY_SALES
			--FIRST_VALUE(sum(sales)) OVER (PARTITION by KIND_OF_BUSINESS order by sales_month)
		FROM
			RETAIL_SALES
		WHERE
			KIND_OF_BUSINESS IN (
				'Women''s clothing stores',
				'Men''s clothing stores'
			)
		GROUP BY
			1,
			2
	)