SELECT
	SALES_MONTH,
	sales,
	count(SALES) OVER (
		ORDER BY
			SALES_MONTH ROWS BETWEEN 11 PRECEDING
			AND CURRENT ROW
	) as count_months_in_ltm,
	round(AVG(SALES) OVER (
		ORDER BY
			SALES_MONTH ROWS BETWEEN 11 PRECEDING
			AND CURRENT ROW
	), 2) as avg_of_ltm,
	MAX(SALES) OVER (
		ORDER BY
			SALES_MONTH ROWS BETWEEN 11 PRECEDING
			AND CURRENT ROW
	) as max_of_ltm
FROM
	RETAIL_SALES
WHERE
	KIND_OF_BUSINESS = 'Women''s clothing stores'