SELECT
	SALES_MONTH,
	SALES,
	LAG(SALES_MONTH) OVER (
		ORDER BY
			SALES_MONTH
	) AS PREVIOUS_MONTH,
	LAG(SALES) OVER (
		ORDER BY
			SALES_MONTH
	) AS PREVIOUS_MONTH_SALES,
	round(SALES / LAG(SALES) OVER (
		ORDER BY
			SALES_MONTH
	) - 1,2) *100 AS MoM
FROM
	RETAIL_SALES
WHERE
	KIND_OF_BUSINESS = 'Book stores'