SELECT
	FIRST_CENTURY_COHORT,
	PERIOD,
	FIRST_VALUE(COHORT_RETAINED) OVER (
		PARTITION BY
			FIRST_CENTURY_COHORT
		ORDER BY
			PERIOD
	) AS COHORT_SIZE,
	COHORT_RETAINED,
	COHORT_RETAINED * 1.00 / FIRST_VALUE(COHORT_RETAINED) OVER (
		PARTITION BY
			FIRST_CENTURY_COHORT
		ORDER BY
			PERIOD
	) AS PCT_RETAINED
FROM
	(
		SELECT
			DATE_PART('century', A.FIRST_TERM) AS FIRST_CENTURY_COHORT,
			COALESCE(DATE_PART('year', AGE (C.DATE, A.FIRST_TERM)), 0) AS PERIOD,
			COUNT(DISTINCT A.ID_BIOGUIDE) AS COHORT_RETAINED
		FROM
			(
				SELECT
					ID_BIOGUIDE,
					MIN(TERM_START) AS FIRST_TERM
				FROM
					LEGISLATORS_TERMS
					--WHERE
					--	ID_BIOGUIDE IN ('B000944', 'L000200')
				GROUP BY
					1
			) A
			JOIN LEGISLATORS_TERMS B ON A.ID_BIOGUIDE = B.ID_BIOGUIDE
			LEFT JOIN DATE_DIM C ON C.DATE BETWEEN B.TERM_START AND B.TERM_END
			AND C.MONTH_NAME = 'December'
			AND C.DAY_OF_MONTH = 31
		GROUP BY
			1,
			2
	)