/*SELECT
DATE_PART('year', SALES_MONTH),
SUM(
CASE
WHEN KIND_OF_BUSINESS = 'Women''s clothing stores' THEN SALES
END
) - SUM(
CASE
WHEN KIND_OF_BUSINESS = 'Men''s clothing stores' THEN SALES
END
) AS WOMENS_MINUS_MENS
FROM
RETAIL_SALES
GROUP BY
1
*/
SELECT
	*,
	WOMENS_SALES / MENS_SALES AS WOMEN_TIMES_MEN,
	(WOMENS_SALES / MENS_SALES - 1) * 100 AS PCT_OF_DIFF
FROM
	(
		SELECT
			DATE_PART('year', SALES_MONTH),
			SUM(
				CASE
					WHEN KIND_OF_BUSINESS = 'Men''s clothing stores' THEN SALES
				END
			) AS MENS_SALES,
			SUM(
				CASE
					WHEN KIND_OF_BUSINESS = 'Women''s clothing stores' THEN SALES
				END
			) AS WOMENS_SALES
		FROM
			RETAIL_SALES
		WHERE
			SALES_MONTH <= '2019-12-01'
		GROUP BY
			1
	)
ORDER BY
	1
LIMIT
	5