SELECT
	AA.COHORT_CENTURY,
	ROUND(REP_AND_SEN_5_YR * 1.00 / REP, 4) AS PCT_5_YR,
	ROUND(REP_AND_SEN_10_YR * 1.00 / REP, 4) AS PCT_10_YR,
	ROUND(REP_AND_SEN_15_YR * 1.00 / REP, 4) AS PCT_15_YR
FROM
	(
		SELECT
			DATE_PART('century', A.FIRST_TERM) AS COHORT_CENTURY,
			COUNT(DISTINCT A.ID_BIOGUIDE) AS REP
		FROM
			(
				SELECT
					ID_BIOGUIDE,
					MIN(TERM_START) AS FIRST_TERM
				FROM
					LEGISLATORS_TERMS
				WHERE
					TERM_TYPE = 'rep'
				GROUP BY
					1
			) A
		GROUP BY
			1
	) AA
	LEFT JOIN (
		SELECT
			DATE_PART('century', B.FIRST_TERM) AS COHORT_CENTURY,
			COUNT(
				DISTINCT CASE
					WHEN AGE (C.TERM_START, B.FIRST_TERM) <= INTERVAL '5 years' THEN B.ID_BIOGUIDE
				END
			) AS REP_AND_SEN_5_YR,
			COUNT(
				DISTINCT CASE
					WHEN AGE (C.TERM_START, B.FIRST_TERM) <= INTERVAL '10 years' THEN B.ID_BIOGUIDE
				END
			) AS REP_AND_SEN_10_YR,
			COUNT(
				DISTINCT CASE
					WHEN AGE (C.TERM_START, B.FIRST_TERM) <= INTERVAL '15 years' THEN B.ID_BIOGUIDE
				END
			) AS REP_AND_SEN_15_YR
		FROM
			(
				SELECT
					ID_BIOGUIDE,
					MIN(TERM_START) AS FIRST_TERM
				FROM
					LEGISLATORS_TERMS
				WHERE
					TERM_TYPE = 'rep'
				GROUP BY
					1
			) B
			JOIN LEGISLATORS_TERMS C ON B.ID_BIOGUIDE = C.ID_BIOGUIDE
			AND C.TERM_TYPE = 'sen'
			AND C.TERM_START > B.FIRST_TERM
			--AND age(C.TERM_START, B.first_term) <= interval '10 years'
		GROUP BY
			1
	) BB ON AA.COHORT_CENTURY = BB.COHORT_CENTURY